/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADefFctDf extends PDf
{
    private TId _id_;
    private TParO _parO_;
    private PLdv _ldv_;
    private TParF _parF_;
    private PLdvo _ldvo_;
    private PIbloc _ibloc_;

    public ADefFctDf()
    {
        // Constructor
    }

    public ADefFctDf(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TParO _parO_,
        @SuppressWarnings("hiding") PLdv _ldv_,
        @SuppressWarnings("hiding") TParF _parF_,
        @SuppressWarnings("hiding") PLdvo _ldvo_,
        @SuppressWarnings("hiding") PIbloc _ibloc_)
    {
        // Constructor
        setId(_id_);

        setParO(_parO_);

        setLdv(_ldv_);

        setParF(_parF_);

        setLdvo(_ldvo_);

        setIbloc(_ibloc_);

    }

    @Override
    public Object clone()
    {
        return new ADefFctDf(
            cloneNode(this._id_),
            cloneNode(this._parO_),
            cloneNode(this._ldv_),
            cloneNode(this._parF_),
            cloneNode(this._ldvo_),
            cloneNode(this._ibloc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefFctDf(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TParO getParO()
    {
        return this._parO_;
    }

    public void setParO(TParO node)
    {
        if(this._parO_ != null)
        {
            this._parO_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parO_ = node;
    }

    public PLdv getLdv()
    {
        return this._ldv_;
    }

    public void setLdv(PLdv node)
    {
        if(this._ldv_ != null)
        {
            this._ldv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldv_ = node;
    }

    public TParF getParF()
    {
        return this._parF_;
    }

    public void setParF(TParF node)
    {
        if(this._parF_ != null)
        {
            this._parF_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parF_ = node;
    }

    public PLdvo getLdvo()
    {
        return this._ldvo_;
    }

    public void setLdvo(PLdvo node)
    {
        if(this._ldvo_ != null)
        {
            this._ldvo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldvo_ = node;
    }

    public PIbloc getIbloc()
    {
        return this._ibloc_;
    }

    public void setIbloc(PIbloc node)
    {
        if(this._ibloc_ != null)
        {
            this._ibloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ibloc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._parO_)
            + toString(this._ldv_)
            + toString(this._parF_)
            + toString(this._ldvo_)
            + toString(this._ibloc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._parO_ == child)
        {
            this._parO_ = null;
            return;
        }

        if(this._ldv_ == child)
        {
            this._ldv_ = null;
            return;
        }

        if(this._parF_ == child)
        {
            this._parF_ = null;
            return;
        }

        if(this._ldvo_ == child)
        {
            this._ldvo_ = null;
            return;
        }

        if(this._ibloc_ == child)
        {
            this._ibloc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._parO_ == oldChild)
        {
            setParO((TParO) newChild);
            return;
        }

        if(this._ldv_ == oldChild)
        {
            setLdv((PLdv) newChild);
            return;
        }

        if(this._parF_ == oldChild)
        {
            setParF((TParF) newChild);
            return;
        }

        if(this._ldvo_ == oldChild)
        {
            setLdvo((PLdvo) newChild);
            return;
        }

        if(this._ibloc_ == oldChild)
        {
            setIbloc((PIbloc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
