/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AExprEtExpr1 extends PExpr1
{
    private PExpr1 _expr1_;
    private TEt _et_;
    private PExpr2 _expr2_;

    public AExprEtExpr1()
    {
        // Constructor
    }

    public AExprEtExpr1(
        @SuppressWarnings("hiding") PExpr1 _expr1_,
        @SuppressWarnings("hiding") TEt _et_,
        @SuppressWarnings("hiding") PExpr2 _expr2_)
    {
        // Constructor
        setExpr1(_expr1_);

        setEt(_et_);

        setExpr2(_expr2_);

    }

    @Override
    public Object clone()
    {
        return new AExprEtExpr1(
            cloneNode(this._expr1_),
            cloneNode(this._et_),
            cloneNode(this._expr2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprEtExpr1(this);
    }

    public PExpr1 getExpr1()
    {
        return this._expr1_;
    }

    public void setExpr1(PExpr1 node)
    {
        if(this._expr1_ != null)
        {
            this._expr1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr1_ = node;
    }

    public TEt getEt()
    {
        return this._et_;
    }

    public void setEt(TEt node)
    {
        if(this._et_ != null)
        {
            this._et_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._et_ = node;
    }

    public PExpr2 getExpr2()
    {
        return this._expr2_;
    }

    public void setExpr2(PExpr2 node)
    {
        if(this._expr2_ != null)
        {
            this._expr2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr1_)
            + toString(this._et_)
            + toString(this._expr2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr1_ == child)
        {
            this._expr1_ = null;
            return;
        }

        if(this._et_ == child)
        {
            this._et_ = null;
            return;
        }

        if(this._expr2_ == child)
        {
            this._expr2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr1_ == oldChild)
        {
            setExpr1((PExpr1) newChild);
            return;
        }

        if(this._et_ == oldChild)
        {
            setEt((TEt) newChild);
            return;
        }

        if(this._expr2_ == oldChild)
        {
            setExpr2((PExpr2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
