/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIaffInstBloc extends PInstBloc
{
    private PIaff _iaff_;

    public AIaffInstBloc()
    {
        // Constructor
    }

    public AIaffInstBloc(
        @SuppressWarnings("hiding") PIaff _iaff_)
    {
        // Constructor
        setIaff(_iaff_);

    }

    @Override
    public Object clone()
    {
        return new AIaffInstBloc(
            cloneNode(this._iaff_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIaffInstBloc(this);
    }

    public PIaff getIaff()
    {
        return this._iaff_;
    }

    public void setIaff(PIaff node)
    {
        if(this._iaff_ != null)
        {
            this._iaff_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iaff_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iaff_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iaff_ == child)
        {
            this._iaff_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iaff_ == oldChild)
        {
            setIaff((PIaff) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
