/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIappInst extends PInst
{
    private PIapp _iapp_;

    public AIappInst()
    {
        // Constructor
    }

    public AIappInst(
        @SuppressWarnings("hiding") PIapp _iapp_)
    {
        // Constructor
        setIapp(_iapp_);

    }

    @Override
    public Object clone()
    {
        return new AIappInst(
            cloneNode(this._iapp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIappInst(this);
    }

    public PIapp getIapp()
    {
        return this._iapp_;
    }

    public void setIapp(PIapp node)
    {
        if(this._iapp_ != null)
        {
            this._iapp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iapp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iapp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iapp_ == child)
        {
            this._iapp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iapp_ == oldChild)
        {
            setIapp((PIapp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
