/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIsiInstBloc extends PInstBloc
{
    private PIsi _isi_;

    public AIsiInstBloc()
    {
        // Constructor
    }

    public AIsiInstBloc(
        @SuppressWarnings("hiding") PIsi _isi_)
    {
        // Constructor
        setIsi(_isi_);

    }

    @Override
    public Object clone()
    {
        return new AIsiInstBloc(
            cloneNode(this._isi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIsiInstBloc(this);
    }

    public PIsi getIsi()
    {
        return this._isi_;
    }

    public void setIsi(PIsi node)
    {
        if(this._isi_ != null)
        {
            this._isi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._isi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._isi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._isi_ == child)
        {
            this._isi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._isi_ == oldChild)
        {
            setIsi((PIsi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
