/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AItqInst extends PInst
{
    private PItq _itq_;

    public AItqInst()
    {
        // Constructor
    }

    public AItqInst(
        @SuppressWarnings("hiding") PItq _itq_)
    {
        // Constructor
        setItq(_itq_);

    }

    @Override
    public Object clone()
    {
        return new AItqInst(
            cloneNode(this._itq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAItqInst(this);
    }

    public PItq getItq()
    {
        return this._itq_;
    }

    public void setItq(PItq node)
    {
        if(this._itq_ != null)
        {
            this._itq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._itq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._itq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._itq_ == child)
        {
            this._itq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._itq_ == oldChild)
        {
            setItq((PItq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
