/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALdeListLde extends PLde
{
    private PExpr _expr_;
    private PLde _lde_;

    public ALdeListLde()
    {
        // Constructor
    }

    public ALdeListLde(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") PLde _lde_)
    {
        // Constructor
        setExpr(_expr_);

        setLde(_lde_);

    }

    @Override
    public Object clone()
    {
        return new ALdeListLde(
            cloneNode(this._expr_),
            cloneNode(this._lde_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALdeListLde(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public PLde getLde()
    {
        return this._lde_;
    }

    public void setLde(PLde node)
    {
        if(this._lde_ != null)
        {
            this._lde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lde_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._lde_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._lde_ == child)
        {
            this._lde_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._lde_ == oldChild)
        {
            setLde((PLde) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
