/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALdiListLdi extends PLdi
{
    private PInstBloc _instBloc_;
    private PLdi _ldi_;

    public ALdiListLdi()
    {
        // Constructor
    }

    public ALdiListLdi(
        @SuppressWarnings("hiding") PInstBloc _instBloc_,
        @SuppressWarnings("hiding") PLdi _ldi_)
    {
        // Constructor
        setInstBloc(_instBloc_);

        setLdi(_ldi_);

    }

    @Override
    public Object clone()
    {
        return new ALdiListLdi(
            cloneNode(this._instBloc_),
            cloneNode(this._ldi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALdiListLdi(this);
    }

    public PInstBloc getInstBloc()
    {
        return this._instBloc_;
    }

    public void setInstBloc(PInstBloc node)
    {
        if(this._instBloc_ != null)
        {
            this._instBloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instBloc_ = node;
    }

    public PLdi getLdi()
    {
        return this._ldi_;
    }

    public void setLdi(PLdi node)
    {
        if(this._ldi_ != null)
        {
            this._ldi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instBloc_)
            + toString(this._ldi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instBloc_ == child)
        {
            this._instBloc_ = null;
            return;
        }

        if(this._ldi_ == child)
        {
            this._ldi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instBloc_ == oldChild)
        {
            setInstBloc((PInstBloc) newChild);
            return;
        }

        if(this._ldi_ == oldChild)
        {
            setLdi((PLdi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
