/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALdiInstLdi extends PLdi
{
    private PInstBloc _instBloc_;

    public ALdiInstLdi()
    {
        // Constructor
    }

    public ALdiInstLdi(
        @SuppressWarnings("hiding") PInstBloc _instBloc_)
    {
        // Constructor
        setInstBloc(_instBloc_);

    }

    @Override
    public Object clone()
    {
        return new ALdiInstLdi(
            cloneNode(this._instBloc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALdiInstLdi(this);
    }

    public PInstBloc getInstBloc()
    {
        return this._instBloc_;
    }

    public void setInstBloc(PInstBloc node)
    {
        if(this._instBloc_ != null)
        {
            this._instBloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instBloc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instBloc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instBloc_ == child)
        {
            this._instBloc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instBloc_ == oldChild)
        {
            setInstBloc((PInstBloc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
