/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TAl extends Token
{
    public TAl()
    {
        super.setText("alors");
    }

    public TAl(int line, int pos)
    {
        super.setText("alors");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAl(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAl(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAl text.");
    }
}
