/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TEcr extends Token
{
    public TEcr()
    {
        super.setText("ecrire");
    }

    public TEcr(int line, int pos)
    {
        super.setText("ecrire");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEcr(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEcr(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEcr text.");
    }
}
