/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TEnt extends Token
{
    public TEnt()
    {
        super.setText("entier");
    }

    public TEnt(int line, int pos)
    {
        super.setText("entier");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEnt(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEnt(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEnt text.");
    }
}
