/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TFai extends Token
{
    public TFai()
    {
        super.setText("faire");
    }

    public TFai(int line, int pos)
    {
        super.setText("faire");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFai(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFai(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFai text.");
    }
}
