/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TFct extends Token
{
    public TFct()
    {
        super.setText("fonction");
    }

    public TFct(int line, int pos)
    {
        super.setText("fonction");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFct(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFct(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFct text.");
    }
}
