/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TLir extends Token
{
    public TLir()
    {
        super.setText("lire");
    }

    public TLir(int line, int pos)
    {
        super.setText("lire");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLir(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLir(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLir text.");
    }
}
