/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TRet extends Token
{
    public TRet()
    {
        super.setText("retour");
    }

    public TRet(int line, int pos)
    {
        super.setText("retour");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRet(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRet(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRet text.");
    }
}
