/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.parser;

import sc.node.*;
import sc.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 0;
    }

    @Override
    public void caseTEgal(@SuppressWarnings("unused") TEgal node)
    {
        this.index = 1;
    }

    @Override
    public void caseTMoins(@SuppressWarnings("unused") TMoins node)
    {
        this.index = 2;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 3;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 4;
    }

    @Override
    public void caseTInf(@SuppressWarnings("unused") TInf node)
    {
        this.index = 5;
    }

    @Override
    public void caseTEt(@SuppressWarnings("unused") TEt node)
    {
        this.index = 6;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 7;
    }

    @Override
    public void caseTNon(@SuppressWarnings("unused") TNon node)
    {
        this.index = 8;
    }

    @Override
    public void caseTPvir(@SuppressWarnings("unused") TPvir node)
    {
        this.index = 9;
    }

    @Override
    public void caseTVir(@SuppressWarnings("unused") TVir node)
    {
        this.index = 10;
    }

    @Override
    public void caseTAccO(@SuppressWarnings("unused") TAccO node)
    {
        this.index = 11;
    }

    @Override
    public void caseTAccF(@SuppressWarnings("unused") TAccF node)
    {
        this.index = 12;
    }

    @Override
    public void caseTCrochO(@SuppressWarnings("unused") TCrochO node)
    {
        this.index = 13;
    }

    @Override
    public void caseTCrochF(@SuppressWarnings("unused") TCrochF node)
    {
        this.index = 14;
    }

    @Override
    public void caseTParO(@SuppressWarnings("unused") TParO node)
    {
        this.index = 15;
    }

    @Override
    public void caseTParF(@SuppressWarnings("unused") TParF node)
    {
        this.index = 16;
    }

    @Override
    public void caseTSi(@SuppressWarnings("unused") TSi node)
    {
        this.index = 17;
    }

    @Override
    public void caseTAl(@SuppressWarnings("unused") TAl node)
    {
        this.index = 18;
    }

    @Override
    public void caseTSin(@SuppressWarnings("unused") TSin node)
    {
        this.index = 19;
    }

    @Override
    public void caseTTq(@SuppressWarnings("unused") TTq node)
    {
        this.index = 20;
    }

    @Override
    public void caseTFai(@SuppressWarnings("unused") TFai node)
    {
        this.index = 21;
    }

    @Override
    public void caseTRet(@SuppressWarnings("unused") TRet node)
    {
        this.index = 22;
    }

    @Override
    public void caseTFct(@SuppressWarnings("unused") TFct node)
    {
        this.index = 23;
    }

    @Override
    public void caseTEcr(@SuppressWarnings("unused") TEcr node)
    {
        this.index = 24;
    }

    @Override
    public void caseTLir(@SuppressWarnings("unused") TLir node)
    {
        this.index = 25;
    }

    @Override
    public void caseTEnt(@SuppressWarnings("unused") TEnt node)
    {
        this.index = 26;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 27;
    }

    @Override
    public void caseTNombre(@SuppressWarnings("unused") TNombre node)
    {
        this.index = 28;
    }

    @Override
    public void caseTEspace(@SuppressWarnings("unused") TEspace node)
    {
        this.index = 29;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 30;
    }
}
